version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=yourpassword
      - DB_NAME=yourdbname

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: yourdbname
